version: "3.7"
services:
  client:
    build:
      context: ../client-survey-starter/
      dockerfile: Dockerfile
      target: base
    volumes:
      - ../client-survey-starter:/usr/src/app
      - '/usr/src/app/node_modules'
    ports:
      - '8097:3000'
    command: yarn run start
    expose:
      - '3000'
    environment:
      - PORT=3000