version: "3.7"
services:

  fhir-proxy:
    build:
      context: ../fhir-proxy/
      dockerfile: Dockerfile
      target: base
    volumes:
      - ../fhir-proxy/src:/usr/src/app/src
    container_name: ts-node-docker
    expose:
      - '4000'
    ports:
      - '8100:4000'
    command: yarn run docker-dev
    environment:
      - PROXY_PORT=$PROXY_PORT
      - STREAM_KEY=$STREAM_KEY
      - STREAM_TOKEN=$STREAM_TOKEN
  ingress:
    image: nginx:1.17.9-alpine
    ports:
      - "${INGRESS_PORT:-4400}:443"
    volumes:
      - "./config/certs:/certs"
      - "./config/ingress:/etc/nginx/conf.d"
    depends_on:
      - postgres
      - keycloak

  hapi:
    image: "hapiproject/hapi:latest"
    depends_on:
      - postgres
    ports:
      - "8090:8080"
    volumes:
      - "./config/hapi:/data/hapi/"
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
  keycloak:
    image: jboss/keycloak:15.0.2
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_HOSTNAME: "keycloak.local.app:4400"
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_PORT: 5432
      DB_DATABASE: "keycloak"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./config/db:/docker-entrypoint-initdb.d"


volumes:
    postgres-data:


  # synapse:
  #   image: "matrixdotorg/synapse:latest"
  #   container_name: "synapse"
  #   volumes:
  #       - "./config/chat:/data"
  #   environment:
  #       SYNAPSE_SERVER_NAME: "chat.local.me"
  #       SYNAPSE_REPORT_STATS: "yes"
  # For future auth / ingress stuff

  # ingress:
  #   image: nginx:1.17.9-alpine
  #   ports:
  #     - "${INGRESS_PORT:-4400}:443"
  #   volumes:
  #     - "./config/certs:/stayhome-certs"
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - keycloak

  # keycloak:
  #   image: jboss/keycloak:9.0.0
  #   restart: unless-stopped
  #   environment:
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: password
  #     # KEYCLOAK_HOSTNAME: "localhost:4400"
  #     PROXY_ADDRESS_FORWARDING: "true"
  #     DB_VENDOR: "postgres"
  #     DB_ADDR: "postgres"
  #     DB_PORT: 5432
  #     DB_DATABASE: "keycloak"
  #     DB_USER: "postgres"
  #     DB_PASSWORD: "postgres"
  #   depends_on:
  #     - postgres